/**
 * ==================================================================================
 * MOCK PATIENT NOTES DATA
 * ==================================================================================
 * 
 * Mock data for Patient Notes & Documents Management System
 */

import { PatientNote } from './PatientNotesListing';

export const mockPatientNotes: PatientNote[] = [
  {
    id: 'NOTE-001',
    type: 'Patient Notes',
    content: 'Patient called to confirm appointment for crown placement. Confirmed arrival time and pre-appointment instructions.',
    createdDate: '2026-02-01',
    createdBy: 'Emily Davis',
    isSystemGenerated: false,
    hasAttachment: false,
  },
  {
    id: 'NOTE-002',
    type: 'Financial Notes',
    content: 'Payment plan discussed and approved. Patient will pay $200/month for 6 months starting March 2026.',
    createdDate: '2026-01-28',
    createdBy: 'Emily Davis',
    isSystemGenerated: false,
    hasAttachment: false,
  },
  {
    id: 'NOTE-003',
    type: 'Document (Upload)',
    content: 'Insurance card front and back uploaded.',
    documentName: 'Insurance_Card_Jan2026.pdf',
    documentType: 'Insurance Document',
    createdDate: '2026-01-25',
    createdBy: 'Jennifer Martinez',
    isSystemGenerated: false,
    hasAttachment: true,
  },
  {
    id: 'NOTE-004',
    type: 'Responsible Party Notes',
    content: 'Spoke with responsible party regarding outstanding balance. Payment of $500 promised by end of week.',
    createdDate: '2026-01-22',
    createdBy: 'Emily Davis',
    isSystemGenerated: false,
    hasAttachment: false,
  },
  {
    id: 'NOTE-005',
    type: 'System Notes',
    content: 'Appointment scheduled for 02/15/2026 at 10:00 AM - Routine Cleaning and Exam.',
    createdDate: '2026-01-20',
    createdBy: 'System',
    isSystemGenerated: true,
    hasAttachment: false,
  },
  {
    id: 'NOTE-006',
    type: 'Appointment Notes',
    content: 'Patient arrived 15 minutes late. Completed exam but rescheduled cleaning for next week.',
    createdDate: '2026-01-18',
    createdBy: 'Dr. Sarah Sharma',
    isSystemGenerated: false,
    hasAttachment: false,
  },
  {
    id: 'NOTE-007',
    type: 'Document (Scan)',
    content: 'Consent form for root canal procedure scanned.',
    documentName: 'Consent_Form_RootCanal.pdf',
    documentType: 'Consent Form (CF)',
    createdDate: '2026-01-15',
    createdBy: 'Jennifer Martinez',
    isSystemGenerated: false,
    hasAttachment: true,
  },
  {
    id: 'NOTE-008',
    type: 'System Notes',
    content: 'Insurance claim submitted electronically. Claim ID: CLM-78901',
    createdDate: '2026-01-12',
    createdBy: 'System',
    isSystemGenerated: true,
    hasAttachment: false,
  },
  {
    id: 'NOTE-009',
    type: 'Financial Notes',
    content: 'Insurance verification completed. Delta Dental PPO active, $1500 annual max remaining.',
    createdDate: '2026-01-10',
    createdBy: 'Emily Davis',
    isSystemGenerated: false,
    hasAttachment: false,
  },
  {
    id: 'NOTE-010',
    type: 'Patient Notes',
    content: 'Patient requested appointment reminder via text message instead of phone call. Preferences updated in system.',
    createdDate: '2026-01-08',
    createdBy: 'Emily Davis',
    isSystemGenerated: false,
    hasAttachment: false,
  },
  {
    id: 'NOTE-011',
    type: 'Document (Upload)',
    content: 'Medical history form updated with current medications.',
    documentName: 'Medical_History_2026.pdf',
    documentType: 'Medical History Form',
    createdDate: '2026-01-05',
    createdBy: 'Jennifer Martinez',
    isSystemGenerated: false,
    hasAttachment: true,
  },
  {
    id: 'NOTE-012',
    type: 'Responsible Party Notes',
    content: 'Responsible party changed from spouse to self. Billing address updated.',
    createdDate: '2025-12-28',
    createdBy: 'Emily Davis',
    isSystemGenerated: false,
    hasAttachment: false,
  },
  {
    id: 'NOTE-013',
    type: 'System Notes',
    content: 'Automated reminder sent via SMS for upcoming appointment on 02/15/2026.',
    createdDate: '2025-12-20',
    createdBy: 'System',
    isSystemGenerated: true,
    hasAttachment: false,
  },
  {
    id: 'NOTE-014',
    type: 'Appointment Notes',
    content: 'Patient cancelled appointment due to illness. Rescheduled for next available slot.',
    createdDate: '2025-12-15',
    createdBy: 'Emily Davis',
    isSystemGenerated: false,
    hasAttachment: false,
  },
  {
    id: 'NOTE-015',
    type: 'Patient Notes',
    content: 'Patient expressed anxiety about dental procedures. Discussed sedation options for future treatments.',
    createdDate: '2025-12-10',
    createdBy: 'Dr. Sarah Sharma',
    isSystemGenerated: false,
    hasAttachment: false,
  },
];
