// Registry of every runnable utility + the modern categories that replace the
// legacy Utilities dropdown. The dashboard and the generic runner both read from
// here, so adding a utility = adding one entry to UTILITIES (and, if it targets
// a legacy menu path, a `legacyPath` so the old nav item redirects to it).
import {
  Package,
  Receipt,
  Shield,
  Database,
  Building2,
  UserCog,
  DollarSign,
  FileSpreadsheet,
  Plug,
  Zap,
  FileCheck2,
  ShieldCheck,
  ClipboardCheck,
  Users,
  RefreshCw,
  Merge,
  Replace,
  Copy,
  CalendarClock,
  ArrowLeftRight,
  Home,
  Import,
  FileDown,
  Clock,
  ListTodo,
  Phone,
  Globe,
  Rocket,
  type LucideIcon,
} from "lucide-react";
import type { CategoryMeta, UtilityCategoryKey, UtilityDefinition } from "./types";

// ---------------------------------------------------------------------------
// Categories (modern grouping of the 11 legacy functional areas)
// ---------------------------------------------------------------------------

export const CATEGORIES: CategoryMeta[] = [
  { key: "batch-claims", label: "Batch & Claims", description: "Claim submission, eligibility & referrals", icon: Package, accent: "text-[#3A6EA5]" },
  { key: "billing", label: "Billing & Charges", description: "Generate contract & payment-plan charges", icon: Receipt, accent: "text-[#2FB9A7]" },
  { key: "insurance-procedure", label: "Insurance & Procedures", description: "Consolidate plans, remap codes & coverage", icon: Shield, accent: "text-[#EC4899]" },
  { key: "data-migration", label: "Data Migration (PGID)", description: "Copy / move / change setup data between practice groups", icon: Database, accent: "text-[#8B5CF6]" },
  { key: "office-specific", label: "Office-Specific", description: "Operations scoped to a single office", icon: Building2, accent: "text-[#F59E0B]" },
  { key: "user-functions", label: "User Functions", description: "Ticklers, timeclock & staff tools", icon: UserCog, accent: "text-[#3A6EA5]" },
  { key: "fee-schedules", label: "Fee Schedules", description: "Maintain fee schedules & Excel templates", icon: DollarSign, accent: "text-[#2FB9A7]" },
  { key: "integrations", label: "Third-Party & Integrations", description: "Televox & external service connections", icon: Plug, accent: "text-[#8B5CF6]" },
  { key: "launch", label: "Launch", description: "Open external applications & tools", icon: Zap, accent: "text-[#F59E0B]" },
];

export const CATEGORY_MAP: Record<UtilityCategoryKey, CategoryMeta> = CATEGORIES.reduce(
  (m, c) => ((m[c.key] = c), m),
  {} as Record<UtilityCategoryKey, CategoryMeta>,
);

// ---------------------------------------------------------------------------
// Utilities
// ---------------------------------------------------------------------------

export const UTILITIES: UtilityDefinition[] = [
  // ---- Batch & Claims ------------------------------------------------------
  {
    id: "batch-eclaims-new",
    title: "Batch Claims Processing — EClaims (New)",
    description: "Queue and submit electronic dental claims in a single batch.",
    category: "batch-claims",
    icon: FileCheck2,
    kind: "batch",
    legacyPath: "/utilities/batch-claims/eclaims-new",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    officeScoped: true,
    backend: "pending",
    confirmLabel: "Submit batch",
    steps: ["Collecting eligible claims", "Validating payer requirements", "Building 837 payload", "Transmitting to clearinghouse", "Recording submission results"],
    params: [
      { key: "date_from", label: "Service date from", kind: "date", required: true },
      { key: "date_to", label: "Service date to", kind: "date", required: true },
      { key: "provider_id", label: "Provider", kind: "provider" },
      { key: "include_secondary", label: "Include secondary claims", kind: "checkbox", defaultValue: true },
    ],
    keywords: ["837", "electronic", "submit", "clearinghouse"],
  },
  {
    id: "batch-paper-med",
    title: "Batch Claims — Paper / Med EClaims",
    description: "Generate paper claim forms and medical electronic claims in bulk.",
    category: "batch-claims",
    icon: FileCheck2,
    kind: "batch",
    legacyPath: "/utilities/batch-claims/paper-med",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    officeScoped: true,
    backend: "pending",
    steps: ["Collecting claims", "Formatting CMS-1500 / 837P", "Rendering documents", "Recording results"],
    params: [
      { key: "date_from", label: "Service date from", kind: "date", required: true },
      { key: "date_to", label: "Service date to", kind: "date", required: true },
      { key: "claim_type", label: "Claim type", kind: "select", defaultValue: "paper", options: [
        { value: "paper", label: "Paper (CMS-1500)" },
        { value: "med_eclaim", label: "Medical EClaim (837P)" },
      ] },
    ],
    keywords: ["cms-1500", "medical", "paper"],
  },
  {
    id: "eclaims-management",
    title: "EClaims Management",
    description: "Review submitted electronic claims, statuses, rejections and resubmissions.",
    category: "batch-claims",
    icon: ClipboardCheck,
    kind: "batch",
    legacyPath: "/utilities/batch-claims/eclaims-management",
    roles: ["owner", "admin", "manager", "front_desk"],
    officeScoped: true,
    backend: "pending",
    steps: ["Loading claim register", "Reconciling clearinghouse acknowledgements", "Flagging rejections"],
    params: [
      { key: "status", label: "Claim status", kind: "select", defaultValue: "", options: [
        { value: "", label: "All statuses" },
        { value: "accepted", label: "Accepted" },
        { value: "rejected", label: "Rejected" },
        { value: "pending", label: "Pending" },
      ] },
    ],
    keywords: ["status", "rejection", "resubmit"],
  },
  {
    id: "batch-eligibility",
    title: "Batch Eligibility",
    description: "Run insurance eligibility checks for a range of scheduled patients.",
    category: "batch-claims",
    icon: ShieldCheck,
    kind: "batch",
    legacyPath: "/utilities/batch-claims/batch-eligibility",
    roles: ["owner", "admin", "manager", "front_desk"],
    officeScoped: true,
    backend: "pending",
    steps: ["Gathering scheduled patients", "Querying payer eligibility", "Storing responses"],
    params: [
      { key: "date_from", label: "Appointment from", kind: "date", required: true },
      { key: "date_to", label: "Appointment to", kind: "date", required: true },
    ],
    keywords: ["insurance", "verify", "270", "271"],
  },
  {
    id: "close-out-managed-care",
    title: "Close Out Managed Care Claims",
    description: "Finalize and close capitation / managed-care claims for a period.",
    category: "batch-claims",
    icon: FileCheck2,
    kind: "batch",
    legacyPath: "/utilities/batch-claims/close-out-managed-care",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    officeScoped: true,
    backend: "pending",
    confirmLabel: "Close out claims",
    steps: ["Selecting open managed-care claims", "Applying capitation rules", "Closing claims", "Writing audit records"],
    params: [
      { key: "period", label: "Period (YYYY-MM)", kind: "text", required: true, placeholder: "2026-07" },
    ],
    keywords: ["capitation", "managed care", "close"],
  },
  {
    id: "referral-management",
    title: "Referral Management",
    description: "Batch-review and update inbound/outbound referral records.",
    category: "batch-claims",
    icon: ArrowLeftRight,
    kind: "batch",
    legacyPath: "/utilities/batch-claims/referral-management",
    roles: ["owner", "admin", "manager"],
    officeScoped: true,
    backend: "pending",
    steps: ["Loading referrals", "Matching providers", "Updating statuses"],
    keywords: ["referral", "specialist"],
  },

  // ---- Billing & Charges ---------------------------------------------------
  {
    id: "generate-charges-ortho",
    title: "Generate Ortho Payment Plan Charges",
    description: "Post scheduled orthodontic contract charges due in the selected period.",
    category: "billing",
    icon: Receipt,
    kind: "batch",
    legacyPath: "/utilities/generate-contract-charges/ortho-payment-plan",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    officeScoped: true,
    backend: "pending",
    confirmLabel: "Generate charges",
    steps: ["Loading active ortho contracts", "Calculating charges due", "Posting to ledgers", "Summarizing results"],
    params: [
      { key: "charge_through", label: "Post charges due through", kind: "date", required: true },
      { key: "dry_run", label: "Preview only (do not post)", kind: "checkbox", defaultValue: true },
    ],
    keywords: ["orthodontic", "contract", "recurring", "post"],
  },
  {
    id: "generate-charges-regular",
    title: "Generate Regular Payment Plan Charges",
    description: "Post scheduled charges for standard patient payment plans.",
    category: "billing",
    icon: Receipt,
    kind: "batch",
    legacyPath: "/utilities/generate-contract-charges/regular-payment-plan",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    officeScoped: true,
    backend: "pending",
    confirmLabel: "Generate charges",
    steps: ["Loading active payment plans", "Calculating charges due", "Posting to ledgers", "Summarizing results"],
    params: [
      { key: "charge_through", label: "Post charges due through", kind: "date", required: true },
      { key: "dry_run", label: "Preview only (do not post)", kind: "checkbox", defaultValue: true },
    ],
    keywords: ["payment plan", "contract", "recurring"],
  },
  {
    id: "generate-charges-by-practice",
    title: "Generate Charges by Practice",
    description: "Run contract-charge generation across every office in a practice group.",
    category: "billing",
    icon: Building2,
    kind: "batch",
    legacyPath: "/utilities/generate-contract-charges/by-practice",
    roles: ["owner", "admin"],
    destructive: true,
    backend: "pending",
    confirmLabel: "Generate for practice",
    steps: ["Enumerating offices", "Loading contracts per office", "Posting charges", "Aggregating totals"],
    params: [
      { key: "charge_through", label: "Post charges due through", kind: "date", required: true },
      { key: "dry_run", label: "Preview only (do not post)", kind: "checkbox", defaultValue: true },
    ],
    keywords: ["practice group", "all offices", "pgid"],
  },

  // ---- Insurance & Procedures ---------------------------------------------
  {
    id: "consolidate-duplicate-plans",
    title: "Consolidate Duplicate Plans",
    description: "Merge duplicate insurance plan records and repoint their subscribers.",
    category: "insurance-procedure",
    icon: Merge,
    kind: "wizard",
    legacyPath: "/utilities/insurance-procedure/consolidate-duplicate-plans",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    backend: "pending",
    confirmLabel: "Merge plans",
    steps: ["Detecting duplicate plans", "Building merge preview", "Repointing subscribers", "Retiring duplicates"],
    params: [
      { key: "match_on", label: "Match plans on", kind: "select", defaultValue: "carrier_group", options: [
        { value: "carrier_group", label: "Carrier + group number" },
        { value: "name", label: "Plan name" },
      ] },
    ],
    keywords: ["merge", "duplicate", "plan", "cleanup"],
  },
  {
    id: "consolidate-duplicate-carriers",
    title: "Consolidate Duplicate Carriers",
    description: "Merge duplicate insurance carriers and reassign their plans.",
    category: "insurance-procedure",
    icon: Merge,
    kind: "wizard",
    legacyPath: "/utilities/insurance-procedure/consolidate-duplicate-carriers",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    backend: "pending",
    confirmLabel: "Merge carriers",
    steps: ["Detecting duplicate carriers", "Building merge preview", "Reassigning plans", "Retiring duplicates"],
    keywords: ["merge", "duplicate", "carrier"],
  },
  {
    id: "new-plan-assignment",
    title: "New Plan Assignment",
    description: "Bulk-assign a new insurance plan to a group of patients.",
    category: "insurance-procedure",
    icon: ShieldCheck,
    kind: "batch",
    legacyPath: "/utilities/insurance-procedure/new-plan-assignment",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    officeScoped: true,
    backend: "pending",
    steps: ["Selecting target patients", "Applying plan", "Recording assignments"],
    keywords: ["assign", "plan", "bulk"],
  },
  {
    id: "procedure-code-replace",
    title: "Procedure Code Replace",
    description: "Find-and-replace a procedure code across setup and historical data.",
    category: "insurance-procedure",
    icon: Replace,
    kind: "wizard",
    legacyPath: "/utilities/insurance-procedure/procedure-code-replace",
    roles: ["owner", "admin"],
    destructive: true,
    backend: "pending",
    confirmLabel: "Replace code",
    steps: ["Locating usages", "Previewing changes", "Applying replacement", "Verifying integrity"],
    params: [
      { key: "from_code", label: "Replace code", kind: "text", required: true, placeholder: "D1110" },
      { key: "to_code", label: "With code", kind: "text", required: true, placeholder: "D1120" },
      { key: "scope", label: "Scope", kind: "select", defaultValue: "setup", options: [
        { value: "setup", label: "Setup / fee schedules only" },
        { value: "all", label: "Setup + historical transactions" },
      ] },
    ],
    keywords: ["cdt", "remap", "find replace"],
  },
  {
    id: "coverage-category-copy",
    title: "Coverage Category Copy",
    description: "Copy coverage-category configuration from one plan to others.",
    category: "insurance-procedure",
    icon: Copy,
    kind: "wizard",
    legacyPath: "/utilities/insurance-procedure/coverage-category-copy",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    backend: "pending",
    confirmLabel: "Copy coverage",
    steps: ["Reading source coverage", "Building copy preview", "Writing to targets"],
    keywords: ["coverage", "copy", "category"],
  },

  // ---- Data Migration (PGID) ----------------------------------------------
  {
    id: "pgid-change-future-appointments",
    title: "Change Future Appointments",
    description: "Bulk-reassign future appointments to a different provider, operatory or office.",
    category: "data-migration",
    icon: CalendarClock,
    kind: "wizard",
    legacyPath: "/utilities/pgid/change-future-appointments",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    officeScoped: true,
    backend: "pending",
    confirmLabel: "Apply changes",
    steps: ["Selecting future appointments", "Validating target", "Previewing changes", "Applying reassignment"],
    params: [
      { key: "from_date", label: "From date", kind: "date", required: true },
      { key: "from_provider", label: "Source provider", kind: "provider" },
      { key: "to_provider", label: "Target provider", kind: "provider" },
    ],
    keywords: ["reassign", "appointments", "provider"],
  },
  {
    id: "pgid-data-conversion-mapping",
    title: "Data Conversion Mapping",
    description: "Map legacy conversion values to current setup entities before migrating.",
    category: "data-migration",
    icon: ArrowLeftRight,
    kind: "wizard",
    legacyPath: "/utilities/pgid/data-conversion-mapping",
    roles: ["owner", "admin"],
    destructive: true,
    backend: "pending",
    confirmLabel: "Save mapping",
    steps: ["Loading source values", "Matching to targets", "Validating mapping", "Persisting map"],
    keywords: ["conversion", "mapping", "migrate", "import"],
  },
  {
    id: "pgid-change-patient-fee-schedule",
    title: "Change Patient Fee Schedule",
    description: "Move a set of patients from one fee schedule to another.",
    category: "data-migration",
    icon: DollarSign,
    kind: "wizard",
    legacyPath: "/utilities/pgid/change-patient-fee-schedule",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    officeScoped: true,
    backend: "pending",
    confirmLabel: "Change fee schedule",
    steps: ["Selecting patients", "Validating target schedule", "Previewing changes", "Applying"],
    params: [
      { key: "from_schedule", label: "From fee schedule", kind: "text", placeholder: "Schedule name / id" },
      { key: "to_schedule", label: "To fee schedule", kind: "text", required: true, placeholder: "Schedule name / id" },
    ],
    keywords: ["fee schedule", "patients", "move"],
  },
  {
    id: "pgid-change-patient-home-office",
    title: "Change Patient Home Office",
    description: "Transfer patients' home office between offices in the practice group.",
    category: "data-migration",
    icon: Home,
    kind: "wizard",
    legacyPath: "/utilities/pgid/change-patient-home-office",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    backend: "pending",
    confirmLabel: "Transfer patients",
    steps: ["Selecting patients", "Validating destination office", "Previewing changes", "Applying transfer"],
    params: [
      { key: "to_office", label: "Destination office", kind: "office", required: true },
    ],
    keywords: ["home office", "transfer", "move patients"],
  },

  // ---- Office-Specific -----------------------------------------------------
  {
    id: "office-access-dental-direct-claims",
    title: "Access Dental — Direct Claims",
    description: "Generate the Access Dental direct-claims export for the selected office.",
    category: "office-specific",
    icon: FileDown,
    kind: "batch",
    legacyPath: "/utilities/office-specific/access-dental/direct-claims",
    roles: ["owner", "admin", "manager"],
    officeScoped: true,
    backend: "pending",
    steps: ["Collecting claims", "Formatting Access Dental layout", "Writing export file"],
    keywords: ["access dental", "export", "direct claims"],
  },
  {
    id: "office-access-dental-encounter",
    title: "Access Dental — Encounter Info (Cap Plans)",
    description: "Produce capitation-plan encounter data for Access Dental.",
    category: "office-specific",
    icon: FileDown,
    kind: "batch",
    legacyPath: "/utilities/office-specific/access-dental/encounter-info-cap-plans",
    roles: ["owner", "admin", "manager"],
    officeScoped: true,
    backend: "pending",
    steps: ["Selecting capitation encounters", "Formatting encounter file", "Exporting"],
    keywords: ["access dental", "capitation", "encounter"],
  },
  {
    id: "office-dha-reset",
    title: "DHA — Managed Care Claim Reset",
    description: "Reset stuck DHA managed-care claims so they can be resubmitted.",
    category: "office-specific",
    icon: RefreshCw,
    kind: "batch",
    legacyPath: "/utilities/office-specific/dha",
    roles: ["owner", "admin"],
    destructive: true,
    officeScoped: true,
    backend: "pending",
    confirmLabel: "Reset claims",
    steps: ["Selecting stuck DHA claims", "Clearing transmission flags", "Re-queuing"],
    keywords: ["dha", "reset", "managed care"],
  },
  {
    id: "office-cs-benefits-import",
    title: "CS Benefits — Import Patients",
    description: "Import the CS Benefits patient roster into the selected office.",
    category: "office-specific",
    icon: Import,
    kind: "import-export",
    legacyPath: "/utilities/office-specific/cs-benefits",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    officeScoped: true,
    backend: "pending",
    steps: ["Reading upload", "Validating rows", "Importing patients", "Summarizing"],
    params: [
      { key: "file", label: "Roster file", kind: "file", required: true, accept: ".csv,.xls,.xlsx" },
    ],
    keywords: ["cs benefits", "import", "roster"],
  },
  {
    id: "office-corro-maduro",
    title: "Corro Maduro",
    description: "Run the Corro Maduro office-specific export.",
    category: "office-specific",
    icon: FileDown,
    kind: "batch",
    legacyPath: "/utilities/office-specific/corro-maduro",
    roles: ["owner", "admin"],
    officeScoped: true,
    backend: "pending",
    steps: ["Collecting data", "Formatting export", "Writing file"],
    keywords: ["corro maduro"],
  },

  // ---- User Functions ------------------------------------------------------
  {
    id: "user-tickler",
    title: "Tickler",
    description: "Review and process the tickler follow-up queue.",
    category: "user-functions",
    icon: ListTodo,
    kind: "batch",
    legacyPath: "/utilities/user-functions/tickler",
    roles: ["owner", "admin", "manager", "front_desk", "staff"],
    officeScoped: true,
    backend: "pending",
    steps: ["Loading tickler items", "Applying filters", "Preparing worklist"],
    keywords: ["follow up", "reminder", "queue"],
  },
  {
    id: "user-timeclock",
    title: "TimeClock",
    description: "Clock in / out and view your current timeclock status.",
    category: "user-functions",
    icon: Clock,
    kind: "batch",
    legacyPath: "/utilities/user-functions/timeclock",
    roles: ["owner", "admin", "manager", "front_desk", "staff", "doctor", "provider"],
    backend: "pending",
    steps: ["Reading timeclock", "Recording punch"],
    keywords: ["clock in", "clock out", "time"],
  },
  {
    id: "user-timeclock-editor",
    title: "TimeClock Editor",
    description: "Adjust and approve staff timeclock entries.",
    category: "user-functions",
    icon: Clock,
    kind: "batch",
    legacyPath: "/utilities/user-functions/timeclock-editor",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    officeScoped: true,
    backend: "pending",
    confirmLabel: "Save adjustments",
    steps: ["Loading entries", "Applying adjustments", "Recording approvals"],
    keywords: ["timeclock", "approve", "payroll"],
  },

  // ---- Fee Schedules -------------------------------------------------------
  {
    id: "fee-schedule-maintenance",
    title: "Fee Schedule Maintenance",
    description: "Search, review and bulk-adjust fee schedule entries.",
    category: "fee-schedules",
    icon: DollarSign,
    kind: "batch",
    legacyPath: "/utilities/fee-schedule",
    roles: ["owner", "admin", "manager"],
    destructive: true,
    backend: "pending",
    confirmLabel: "Apply adjustment",
    runNote: "For per-code editing use Setup → Fee Schedules. This utility performs bulk percentage adjustments.",
    steps: ["Loading fee schedule", "Calculating adjusted fees", "Previewing", "Writing changes"],
    params: [
      { key: "schedule", label: "Fee schedule", kind: "text", required: true, placeholder: "Schedule name / id" },
      { key: "adjust_pct", label: "Adjust by (%)", kind: "number", required: true, placeholder: "5" },
      { key: "direction", label: "Direction", kind: "select", defaultValue: "increase", options: [
        { value: "increase", label: "Increase" },
        { value: "decrease", label: "Decrease" },
      ] },
    ],
    keywords: ["fee", "bulk", "increase", "decrease"],
  },
  {
    id: "fee-schedule-excel",
    title: "Fee Schedule Excel Template",
    description: "Download the fee schedule import template, then upload a completed file with validation.",
    category: "fee-schedules",
    icon: FileSpreadsheet,
    kind: "import-export",
    legacyPath: "/utilities/fee-schedule-excel",
    roles: ["owner", "admin", "manager"],
    backend: "live",
    runNote: "Template download and upload validation run entirely in the browser — no backend required.",
    keywords: ["excel", "template", "import", "upload", "xls"],
  },

  // ---- Third-Party & Integrations -----------------------------------------
  {
    id: "televox-appointments-download",
    title: "Televox Appointments Download",
    description: "Export the appointment file Televox uses for automated reminders.",
    category: "integrations",
    icon: Phone,
    kind: "integration",
    legacyPath: "/utilities/televox/appointments-download",
    roles: ["owner", "admin", "manager"],
    officeScoped: true,
    backend: "pending",
    steps: ["Connecting to Televox", "Collecting appointments", "Formatting export", "Uploading to Televox"],
    params: [
      { key: "date_from", label: "Appointments from", kind: "date", required: true },
      { key: "date_to", label: "Appointments to", kind: "date", required: true },
    ],
    keywords: ["televox", "reminders", "sync"],
  },
  {
    id: "integration-transworld",
    title: "Transworld",
    description: "Send delinquent-account data to Transworld collections.",
    category: "integrations",
    icon: Globe,
    kind: "integration",
    legacyPath: "/utilities/integrations/transworld",
    roles: ["owner", "admin"],
    destructive: true,
    officeScoped: true,
    backend: "pending",
    confirmLabel: "Send to Transworld",
    steps: ["Connecting to Transworld", "Selecting accounts", "Transmitting", "Recording placements"],
    keywords: ["transworld", "collections"],
  },
  {
    id: "integration-dps-insurance",
    title: "DPS Insurance Verifications",
    description: "Run DPS automated insurance verifications for upcoming appointments.",
    category: "integrations",
    icon: ShieldCheck,
    kind: "integration",
    legacyPath: "/utilities/integrations/dps-insurance",
    roles: ["owner", "admin", "manager", "front_desk"],
    officeScoped: true,
    backend: "pending",
    steps: ["Connecting to DPS", "Submitting verifications", "Storing responses"],
    keywords: ["dps", "verification", "insurance"],
  },
  {
    id: "integration-denticon-download",
    title: "Denticon Download",
    description: "Pull data from a Denticon export for reconciliation.",
    category: "integrations",
    icon: Globe,
    kind: "integration",
    legacyPath: "/utilities/integrations/denticon-download",
    roles: ["owner", "admin"],
    backend: "pending",
    steps: ["Connecting to Denticon", "Downloading dataset", "Validating"],
    keywords: ["denticon", "download", "reconcile"],
  },

  // ---- Launch --------------------------------------------------------------
  {
    id: "launch-appointnow",
    title: "AppointNow",
    description: "Open the AppointNow online-scheduling console.",
    category: "launch",
    icon: Rocket,
    kind: "launch",
    legacyPath: "/utilities/launch/appointnow",
    roles: ["owner", "admin", "manager", "front_desk"],
    backend: "external",
    launchUrl: "https://www.appointnow.com/",
    keywords: ["appointnow", "online scheduling"],
  },
  {
    id: "launch-automated-campaigns",
    title: "Automated Campaigns",
    description: "Open the automated patient-communication campaigns tool.",
    category: "launch",
    icon: Rocket,
    kind: "launch",
    legacyPath: "/utilities/launch/automated-campaigns",
    roles: ["owner", "admin", "manager"],
    backend: "external",
    launchUrl: "https://www.solutionreach.com/",
    keywords: ["campaigns", "marketing", "recall"],
  },
  {
    id: "launch-dentilytics",
    title: "Dentilytics Basic",
    description: "Open Dentilytics practice analytics.",
    category: "launch",
    icon: Rocket,
    kind: "launch",
    legacyPath: "/utilities/launch/dentilytics",
    roles: ["owner", "admin", "manager"],
    backend: "external",
    launchUrl: "https://www.dentilytics.com/",
    keywords: ["dentilytics", "analytics"],
  },
  {
    id: "launch-dentiray",
    title: "Dentiray Classic",
    description: "Open the Dentiray imaging viewer.",
    category: "launch",
    icon: Rocket,
    kind: "launch",
    legacyPath: "/utilities/launch/dentiray",
    roles: ["owner", "admin", "manager", "doctor", "provider"],
    backend: "external",
    launchUrl: "https://www.dentiray.com/",
    keywords: ["dentiray", "imaging"],
  },
  {
    id: "launch-apteryx-dcv",
    title: "Imaging — ApteryxDCV",
    description: "Launch the ApteryxDCV imaging system.",
    category: "launch",
    icon: Rocket,
    kind: "launch",
    legacyPath: "/utilities/launch/apteryx-dcv",
    roles: ["owner", "admin", "manager", "doctor", "provider"],
    backend: "external",
    launchUrl: "https://www.apteryx.com/",
    keywords: ["apteryx", "dcv", "imaging"],
  },
  {
    id: "launch-xvw-web",
    title: "Imaging 2 — XVWeb",
    description: "Launch the XVWeb imaging system.",
    category: "launch",
    icon: Rocket,
    kind: "launch",
    legacyPath: "/utilities/launch/xvw-web",
    roles: ["owner", "admin", "manager", "doctor", "provider"],
    backend: "external",
    launchUrl: "https://www.apteryximaging.com/xvweb",
    keywords: ["xvweb", "imaging"],
  },
];

// ---------------------------------------------------------------------------
// Lookups
// ---------------------------------------------------------------------------

export function getUtility(id: string): UtilityDefinition | undefined {
  return UTILITIES.find((u) => u.id === id);
}

export function utilitiesByCategory(category: UtilityCategoryKey): UtilityDefinition[] {
  return UTILITIES.filter((u) => u.category === category);
}

/** All (utility, legacyPath) pairs — used to generate nav redirect routes. */
export function legacyRedirects(): { from: string; to: string }[] {
  return UTILITIES.filter((u) => u.legacyPath).map((u) => ({
    from: u.legacyPath as string,
    to: `/utilities/run/${u.id}`,
  }));
}

export type { LucideIcon };
